
<!-- Marketing Icons Section -->
<div class="row my-4">
  <div class="col-lg-4 mb-4">
    <img src="/img/white-1.jpg" class="img-fluid">
  </div>
  <div class="col-lg-8 mb-4">
    <h2 style="text-align: center; font-size: 24px; font-weight: bold; color: #51210d;">Make free calls to the Philippines</h2>
    <br>
    <p style="text-align: center; font-size: 20px;">Free Bee is the newest mobile app that lets you get in touch with your loved ones with FREE calls to the Philippines!</p>

    <ul class="features">
      <li><img src="/img/f1.jpg" class="img-fluid"> Enjoy up to 2-minute FREE calls every day to the Philippines sponsored by advertisers. The number of free calls may vary every day, just tap on the “FREE BEE” button to know if there are more free calls in store for you!</li>
      <li><img src="/img/f2.jpg" class="img-fluid"> For an ad-free calling experience, affordable call rates are available for as low as USD 0.01 per minute!</li>
      <li><img src="/img/f3.jpg" class="img-fluid"> Call your loved ones in their landline or cellphone numbers even though they are not connected in the internet.</li>
    </ul>

    <p style="text-align: center; font-size: 20px; font-weight: bold; color: #51210d;">DOWNLOAD NOW!</p>

    <div class="row my-4">
      <div style="text-align: center;" class="col-lg-2">
      </div>
      <div style="text-align: center;" class="col-lg-4">
        <img src="/img/iosappstore.png" class="img-fluid">
      </div>
      <div style="text-align: center;" class="col-lg-4">
        <img src="/img/gplaybadge.png" class="img-fluid">
      </div>
      <div style="text-align: center;" class="col-lg-2">
      </div>
    </div>
  </div>
</div>
<!-- /.row -->

<!-- Call to Action Section -->
<div class="row mb-4">
  <div class="col-lg-12">
    <h3 class="text-center" style="text-align: center; font-size: 24px; font-weight: bold; color: #51210d;">Free Bee Call Packages</h3>
    <br>
    <p class="text-center" style="text-align: center; font-size: 20px;">Stay connected to your loved ones in the Philippines with affordable call packages.*</p>

    <div class="row my-4">
      <div class="col-lg-4">
        <a href="https://www.smartworld247.com/freebee" target="_blank"><img src="/img/l1.png" class="img-fluid"></a>
      </div>
      <div class="col-lg-4">
        <a href="https://www.smartworld247.com/freebee" target="_blank"><img src="/img/l2.png" class="img-fluid"></a>
      </div>
      <div class="col-lg-4">
        <a href="https://www.smartworld247.com/freebee" target="_blank"><img src="/img/l3.png" class="img-fluid"></a>
      </div>
    </div>
    <br>
    <p class="text-center">*Free Bee currently supports voice calls to PLDT Landline, Smart, TNT, Sun cellular numbers in the Philippines.</p>
    <br>
    <br>
    <br>
  </div>
</div>
