<div class="row">
   <div class="col-sm-6">
        <?php if($this->totalItemCount<=0): ?>
        <div>Showing 0 entries</div>
        <?php else: ?>
        <?php $temp = $this->current * $this->itemCountPerPage; ?>
        <div>Showing <?php echo (($temp) - $this->itemCountPerPage) + 1 ; ?> to <?php echo ($this->totalItemCount < $temp) ? $this->totalItemCount : $temp; ?> of <?php echo $this->totalItemCount; ?> <?php echo $this->totalItemCount<=1 ? 'entry' : 'entries'; ?></div>
        <?php endif; ?>
   </div>
   <div class="col-sm-6">
        <nav aria-label="Page navigation example">
            <?php if ($this->pageCount): ?>
            <ul class="pagination justify-content-end">
                <?php if (isset($this->previous)): ?>
                    <li class="page-item">
                        <a class="page-link" href="<?php echo $this->url($this->route, array('action' => 'index', 'page' => $this->previous)); ?>">
                            <<
                        </a>
                    </li>
                <?php else: ?>
                    <li class="page-item disabled">
                        <a class="page-link" href="#">
                            <<
                        </a>
                    </li>
                <?php endif; ?>
                <?php foreach ($this->pagesInRange as $page): ?>
                    <?php if ($page != $this->current): ?>
                        <li class="page-item">
                            <a class="page-link" href="<?php echo $this->url($this->route, array('action' => 'index', 'page' => $page)); ?>">
                                <?php echo $page; ?>
                            </a>
                        </li>
                    <?php else: ?>
                        <li class="page-item active">
                            <a class="page-link" href="#"><?php echo $page; ?></a>
                        </li>
                    <?php endif; ?>
                <?php endforeach; ?>
                <?php if (isset($this->next)): ?>
                    <li class="page-item">
                        <a class="page-link" href="<?php echo $this->url($this->route, array('action' => 'index', 'page' => $this->next)); ?>">
                            >>
                        </a>
                    </li>
                <?php else: ?>
                    <li class="page-item disabled">
                        <a class="page-link" href="#">
                            >>
                        </a>
                    </li>
                <?php endif; ?>
            </ul>
            <?php endif; ?>
        </nav>
    </div>
</div>
