<h1 class="mt-4 mb-3">Login
</h1>

<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="<?php echo $this->url('home'); ?>">Home</a>
  </li>
  <li class="breadcrumb-item active">Login</li>
</ol>

<div class="row">
  <div class="col-lg-8 mb-4">
    <?php
    $form->setAttribute('action', $this->url('login'));
    $form->setAttribute('id', 'login');
    $form->setAttribute('name', 'login');
    $form->prepare();
    echo $this->form()->openTag($form);
    ?>
    <div class="control-group form-group">
      <div class="controls">
          <?= $this->formLabel($form->get('email')) ?>
          <?= $this->formElement($form->get('email')) ?>
          <?= $this->formElementErrors()->render($form->get('email'), ['class' => 'help-block']) ?>
        </div>
      </div>
      <div class="control-group form-group">
        <div class="controls">
          <?= $this->formLabel($form->get('password')) ?>
          <?= $this->formElement($form->get('password')) ?>
          <?= $this->formElementErrors()->render($form->get('password'), ['class' => 'help-block']) ?>
        </div>
      </div>
      <div class="control-group form-group">
        <div class="controls">
          <label>
            <?= $this->formElement($form->get('remember_me')); ?>
            Remember Password
          </label>
        </div>
      </div>
      <?= $this->formElement($form->get('redirect_url')); ?>
      <?= $this->formElement($form->get('csrf')) ?>
      <?php echo $this->formSubmit($form->get('submit')); ?>
    <?php echo $this->form()->closeTag();?>
    <div class="text-center">
      <a class="d-block small" href="<?php echo $this->url('community', array('action' => 'ofw')); ?>">Regist as O.F.W.</a>
      <a class="d-block small" href="<?php echo $this->url('community', array('action' => 'volunteer')); ?>">Regist as Volunteer</a>
      <a class="d-block small" href="<?php echo $this->url('forgot-password'); ?>">Forgot Password?</a>
    </div>
  </div>

  <div class="col-lg-4 mb-4">
    <h3>Welcome Back</h3>
    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
  </div>
</div>
